name: CI
on:
  - push
  - pull_request
jobs:
  test:
    name: Julia ${{ matrix.version }} - ${{ matrix.os }} - ${{ matrix.arch }} - ${{ github.event_name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        version:
          - '1.2'
          - '1.6'
          - 'nightly'
        os:
          - ubuntu-latest
          #- macOS-latest
        arch:
          - x64
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.version }}
          arch: ${{ matrix.arch }}
      - uses: actions/cache@v1
        env:
          cache-name: cache-artifacts
        with:
          path: ~/.julia/artifacts
          key: ${{ runner.os }}-test-${{ env.cache-name }}-${{ hashFiles('**/Project.toml') }}
          restore-keys: |
            ${{ runner.os }}-test-${{ env.cache-name }}-
            ${{ runner.os }}-test-
            ${{ runner.os }}-
      - run: |
          deps/getgrasp.sh
      - uses: julia-actions/julia-buildpkg@v1
        env:
          GRASP: ${{ github.workspace }}/deps/grasp
      - run: ldd ./test/binaries/test-readrwfn
      # ------------------------------------------------------------------------
      # SSH into the GitHub Actions runner. The removal of the MS repo is
      # necessary to avoid errors updating the APT cache (Error 100).
      # ------------------------------------------------------------------------
      # - run: ls /etc/apt/sources.list.d/
      # - run: cat /etc/apt/sources.list.d/*
      # - run: sudo rm -vf /etc/apt/sources.list.d/microsoft*
      # - run: sudo apt-get update
      # - uses: mxschmitt/action-tmate@v3
      # ------------------------------------------------------------------------
      - run: ./test/binaries/test-readrwfn test/grasp/mixing/rwfn.out
      - uses: julia-actions/julia-runtest@v1
      - uses: julia-actions/julia-processcoverage@v1
      - uses: codecov/codecov-action@v1
        with:
          file: lcov.info
  # docs:
  #   name: Documentation
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: julia-actions/setup-julia@v1
  #       with:
  #         version: '1.6'
  #     - run: |
  #         julia --project=docs -e '
  #           using Pkg
  #           Pkg.develop(PackageSpec(path=pwd()))
  #           Pkg.instantiate()'
  #     - run: julia --project=docs docs/make.jl
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #         DOCUMENTER_KEY: ${{ secrets.DOCUMENTER_KEY }}
  # doctests:
  #   name: Doctests
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: julia-actions/setup-julia@v1
  #       with:
  #         version: '1.4'
  #     - run: |
  #         julia --project=docs -e '
  #           using Pkg
  #           Pkg.develop(PackageSpec(path=pwd()))
  #           Pkg.instantiate()'
  #     - run: |
  #         julia --project=docs -e '
  #           using Documenter: DocMeta, doctest
  #           using GRASP
  #           DocMeta.setdocmeta!(GRASP, :DocTestSetup, :(using GRASP); recursive=true)
  #           doctest(GRASP)'
